import type { InspirationCopy } from "@/lib/inspirationCopy";

export const INSPIRATION_COPY_EN: Record<string, InspirationCopy> = {
  santorini: {
    name: "Santorini",
    story: [
      "White houses, blue domes and the caldera view – Santorini feels like a postcard that came to life.",
      "Evenings in Oia, when the sun sinks into the sea, stay with you. By day: vineyards, small bays and the story of a volcanic island.",
    ],
    mustSee: [
      "Akrotiri: Minoan town buried after the Bronze Age eruption (excavation, fixed opening hours).",
      "Caldera view from Fira or Imerovigli, especially as the light fades.",
      "Oia in the evening: plan sunset from the Agios Nikolaos castle ruins.",
      "Archaeological Museum of Fira: frescoes and finds from Akrotiri at a glance.",
      "Museum of Prehistoric Thera: geology and settlement context.",
      "Wine tasting in Pyrgos or Megalochori (Assyrtiko, Aidani).",
      "Volcanic islet Nea Kameni: organised boat trip with a short crater walk.",
      "Amoudi Bay below Oia: steep descent, fish tavernas by the water.",
      "Prophet Elias monastery (highest point): views across the Cyclades.",
      "Ancient Thera on Mesa Vouno: Classical–Roman ruins above the sea.",
    ],
    history: [
      "In the Late Bronze Age a Minoan-influenced town stood on Thera (Akrotiri); the huge eruption in the second half of the 2nd millennium BCE buried the settlement under pumice and ash and shaped today’s caldera.",
      "In antiquity the island was called Thera; in the Middle Ages Venetians settled here and left fortified sites such as Pyrgos. From 1566 to 1821 the Cycladic island belonged to the Ottoman Empire.",
      "In 1830 Thera became part of independent Greece; mass tourism arrived in the 20th century, with ongoing debates on carrying capacity, water and heritage protection.",
    ],
  },
  nordlichter: {
    name: "Northern Lights",
    story: [
      "Green-violet bands in the night sky: the aurora is a nature experience many travellers want once in a lifetime.",
      "Best chances are inside the Arctic Circle in the dark season – with patience, warm clothes and a flexible route.",
    ],
    mustSee: [
      "Tromsø (Norway): aurora season September–March, many guided trips inland.",
      "Abisko (Sweden): statistically clearer nights thanks to föhn off the mountains.",
      "Rovaniemi region (Finland): reindeer farms plus northern-lights hunts.",
      "Lofoten: fjords and fishing villages under the aurora (weather dependent).",
      "Senja: quieter than Tromsø, steep coast.",
      "Kiruna and the Icehotel area: long polar nights, solid infrastructure.",
      "Iceland (Þingvellir, south coast): aurora next to geysers and glaciers (no guarantee).",
      "Fairbanks (Alaska): continental cold, clear winter nights.",
      "Yellowknife (Canada): established aurora tourism.",
      "Use space-weather forecasts (e.g. NOAA OVATION, local apps), not just a weather app.",
    ],
    history: [
      "Norse sources (Snorri Sturluson, 13th c.) link the aurora to myth; medieval European chroniclers often read red auroras as ill omens.",
      "From the 17th century naturalists tied the displays to Earth’s magnetic field; around 1900 Kristian Birkeland modelled charged solar particles entering the polar atmosphere and exciting gas (green from oxygen is typical).",
      "Modern satellites measure solar wind and CMEs; trips cluster at geomagnetic latitudes 65–75° N in the equinox–winter season.",
    ],
  },
  venedig: {
    name: "Venice",
    story: [
      "Gondolas, narrow lanes and square serenades: Venice is a labyrinth of water and stone.",
      "Beyond Rialto and St Mark’s, drifting through Cannaregio is worth it – less bustle, more everyday life.",
    ],
    mustSee: [
      "St Mark’s Basilica and Campanile (plan tickets and queues).",
      "Doge’s Palace across the Bridge of Sighs to the prison.",
      "Rialto Bridge and Mercato di Rialto in the morning.",
      "Accademia Bridge: classic view of the Grand Canal.",
      "Basilica Santa Maria della Salute (plague votive church, 1631–1687).",
      "Ghetto Nuovo: Europe’s first documented Jewish residential quarter (1516).",
      "Scuola Grande di San Rocco: Tintoretto cycles.",
      "Biennale Gardens (Giardini) and Arsenale in art-biennale years.",
      "Vaporetto line 1: the whole Grand Canal as a ride.",
      "Murano (glass) and Burano (lace, colour) by waterbus.",
    ],
    history: [
      "The lagoon islands were settled from late antiquity; after Lombard and Byzantine influence the community traditionally elected its first doge in 697 and grew into a maritime republic.",
      "In the High Middle Ages and early modern period Venice controlled trade routes into the eastern Mediterranean; the Fourth Crusade of 1204 ended with the sack of Constantinople under Venetian–French leadership.",
      "In 1797 the republic surrendered to Napoleon (Treaty of Campo Formio); then Austrian rule, and from 1866 union with the Kingdom of Italy. The MOSE flood barriers at the lagoon inlets went into operation in 2020.",
    ],
  },
  malediven: {
    name: "Maldives",
    story: [
      "Turquoise water, fine sand and atolls – the Maldives stand for calm and underwater worlds.",
      "Snorkelling and diving straight from the bungalow make many stays unforgettable.",
    ],
    mustSee: [
      "House-reef snorkelling (sharks/rays only with a guide and rules).",
      "Bioluminescent beaches (Vaadhoo and others, moon- and plankton-dependent).",
      "Maldivian cultural centre in Malé: boatbuilding and everyday life.",
      "Hukuru Miskiiy (Friday Mosque, 1656) in Malé with coral-stone carving.",
      "Dive sites: Banana Reef, Manta Point (check season).",
      "Island-hopping by speedboat or domestic flight plus seaplane.",
      "Sandbanks at low tide for photos – watch the current.",
      "Thoddoo: agricultural island with melon farms (guest-island tours).",
      "Addu Atoll: historic British radar site, bike tours.",
      "Check sustainability (solar, desalination, the resort’s waste management).",
    ],
    history: [
      "A Buddhist period from about the 5th century CE is archaeologically attested; conversion to Islam is dated to 1153 (tradition of the first Muslim sultan).",
      "Brief Portuguese presence in 1558, then indirect Dutch influence; in 1887 a British protectorate over the sultan. Independence on 26 July 1965, republic in 1968.",
      "The 2004 tsunami devastated many low islands; since then much reclamation and tourism islands with strict zoning.",
    ],
  },
  paris: {
    name: "Paris",
    story: [
      "City of light, museums and cafés: Paris mixes icons like the Eiffel Tower and the Louvre with neighbourhood charm.",
      "A walk along the Seine or through Le Marais often brings the best unplanned moments.",
    ],
    mustSee: [
      "Louvre (book a time slot) and the Tuileries Garden.",
      "Musée d’Orsay in the former station hall (Impressionism).",
      "Notre-Dame (exterior and west façade accessible again after the 2019 fire; interior depends on the phase).",
      "Sainte-Chapelle: Gothic stained glass on the Île de la Cité.",
      "Versailles by RER C (palace and gardens, at least half a day).",
      "Montmartre: Sacré-Cœur and Place du Tertre.",
      "Marais: Place des Vosges and the Jewish quarter around Rue des Rosiers.",
      "Promenade Plantée / Coulée Verte as a linear park on a viaduct.",
      "Catacombs (tight, tickets in advance).",
      "Walk the UNESCO Seine banks between Pont de Sully and Pont d’Iéna.",
    ],
    history: [
      "Celtic Parisii settled on the Seine island; Roman Lutetia from the 1st century CE with forum and baths. Charlemagne held an assembly in 798 in the palace chapel.",
      "Capetian kings made Paris the residence; in 1789 the people stormed the Bastille. Baron Haussmann built boulevards and sewers under Napoleon III in the mid-19th century.",
      "The sieges of 1870/71 and the Paris Commune shaped the Third Republic; city and suburbs grew administratively (Grand Paris since 2016).",
    ],
  },
  barcelona: {
    name: "Barcelona",
    story: [
      "Gaudí, beach and Catalan cooking: Barcelona mixes a big city with a Mediterranean feel.",
      "From Park Güell to the Barri Gòtic the city is easy to explore by public transport and on foot.",
    ],
    mustSee: [
      "Sagrada Família (online ticket required).",
      "Park Güell (visited zone needs a ticket).",
      "Casa Batlló and Casa Milà (La Pedrera) on Passeig de Gràcia.",
      "Barri Gòtic: cathedral, Plaça del Rei with medieval palaces.",
      "Museu Picasso in El Born.",
      "Palau de la Música Catalana (Modernisme, guided tours).",
      "Montjuïc: Fundació Joan Miró, Olympic Stadium, Magic Fountain (check times).",
      "Barceloneta beach and the harbour promenade.",
      "Camp Nou / Spotify Camp Nou (stadium tour depending on rebuilding).",
      "Mercat de la Boqueria or Santa Caterina for a market breakfast.",
    ],
    history: [
      "The Roman Colonia Iulia Augusta Faventia Paterna Barcino grew under Augustus; in the Middle Ages Barcelona was capital of the County of Barcelona in the Crown of Aragon.",
      "After the union of Aragon and Castile, Catalonia stayed economically strong; in the War of the Spanish Succession in 1714 the city fell after a siege to Bourbon troops (national day, the Diada).",
      "19th-century industry funded Modernisme (Gaudí and others); the 1992 Olympics drove coastal and infrastructure projects.",
    ],
  },
  amalfi: {
    name: "Amalfi",
    story: [
      "Steep coast, lemon groves and colourful towns: the Amalfi Coast is Italy’s classic for a road-trip feeling with sea views.",
      "Between Positano and Vietri sul Mare every bend waits with a new panorama – sketch the route and stops in advance.",
    ],
    mustSee: [
      "Positano: Chiesa di Santa Maria Assunta with a majolica dome.",
      "Path of the Gods (Sentiero degli Dei): hike Bomerano–Nocelle (bus logistics).",
      "Amalfi: Cathedral of Sant’Andrea with the Cloister of Paradise.",
      "Ravello: Villa Rufolo and Villa Cimbrone (terrace gardens).",
      "Maiori / Minori: Roman villa-maritime traces, less crowded.",
      "Vietri sul Mare: ceramics workshops.",
      "Boat from Salerno to Amalfi/Positano (summer timetable).",
      "Fiordo di Furore: narrow gorge with a bridge on the SS163 (photo stop, watch traffic).",
      "Strada Statale 163: easy for bus drivers, stressful for cars – leave a time buffer.",
      "Limoncello production in Minori or Tramonti (book ahead).",
    ],
    history: [
      "In the early Middle Ages Amalfi grew into a maritime trading republic (de facto 9th–11th c.) with posts in the eastern Mediterranean; the Amalfitan Tables (medieval maritime-law fragments, preserved e.g. in Pisa and Ravenna) are linked to Amalfi.",
      "The Norman conquest of southern Italy (11th c.) and later the 1284 battle of Meloria weakened the fleet; 14th-century plagues reduced the population.",
      "In 1997 UNESCO listed the Amalfi Coast as a cultural landscape (terraced orchards, settlements on steep slopes).",
    ],
  },
  hallstatt: {
    name: "Hallstatt",
    story: [
      "Lake reflections, salt mines and an alpine backdrop: Hallstatt draws people with postcard scenery.",
      "Coming early or late pays off if you want the quiet – the village is small, the view is large.",
    ],
    mustSee: [
      "World Heritage viewpoint (postcard view) early morning or evening.",
      "Salzwelten Hallstatt: mine ride on the underground train (tickets).",
      "Pile-dwelling museum on the lake (UNESCO alpine pile dwellings).",
      "St Michael charnel house with stacked bones (opening hours).",
      "Market square with timber façades and the Protestant Christuskirche.",
      "Lakeside walk towards Lahn (quieter than the centre).",
      "Dachstein-Krippenstein: Five Fingers viewing platform (bus/train).",
      "Gosausee as a day trip (car or bus).",
      "Bad Aussee or Altaussee for nearby Salzkammergut scenery.",
      "Boat trip on Lake Hallstatt (seasonal).",
    ],
    history: [
      "Salt mining on the Hallstatt mountain is attested for the earlier Urnfield culture; the term “Hallstatt period” (c. 800–450 BCE) comes from this site.",
      "Celts and later Romans used the deposit; in the Middle Ages the Habsburgs owned the mines. In 1595 almost the whole village burned and was rebuilt on today’s shoreline.",
      "In 1997 UNESCO listed the Hallstatt–Dachstein/Salzkammergut cultural landscape; since the 2010s the municipality has debated overtourism and bus limits.",
    ],
  },
  dubrovnik: {
    name: "Dubrovnik",
    story: [
      "Walls, the Adriatic and cobbles: Dubrovnik joins history with a Mediterranean feel.",
      "The old town is compact – perfect for an unhurried day, then planning the coast onwards.",
    ],
    mustSee: [
      "City-wall circuit (one ticket, fixed opening hours).",
      "Stradun (Placa) as the main axis.",
      "Rector’s Palace (cultural history museum).",
      "Franciscan monastery with one of Europe’s oldest still-working pharmacies.",
      "Sponza Palace (archive / memorial room 1991–1995).",
      "Fort Lovrijenac west of the old town (fortress view).",
      "Srđ cable car: panorama over the roofs.",
      "Lokrum island (botanical garden, Iron Throne replica).",
      "Banje beach or kayaking under the walls.",
      "Game of Thrones locations optional with an early slot (fewer groups).",
    ],
    history: [
      "As Ragusa the city-republic ran long-distance sea trade from the 14th century; in 1416 it banned the slave trade – early for Mediterranean cities.",
      "A 1667 earthquake destroyed much of the town; the baroque skyline came with the rebuild. Independence ended in 1808; in 1815 Ragusa went to Austria, in 1918 to Yugoslavia.",
      "In 1991 the JNA shelled the old town (UNESCO World Heritage since 1979); after the Croatian War came careful stone restoration. In 2023 the city adopted the euro.",
    ],
  },
  "cinque-terre": {
    name: "Cinque Terre",
    story: [
      "Five colourful villages between cliff and Ligurian Sea: Cinque Terre is a hiking and rail classic.",
      "Paths such as the Blue Trail link the towns – good shoes and tickets in advance save stress.",
    ],
    mustSee: [
      "Monterosso al Mare: the only sandy beach, train access.",
      "Vernazza: harbour cove with Castello Doria tower ruin.",
      "Corniglia: more than 380 “Lardarina” steps from the station.",
      "Manarola: postcard viewpoint above the vineyard.",
      "Riomaggiore: Via dell’Amore (sections depending on restoration).",
      "Check the Cinque Terre Card hiking pass for trails and trains.",
      "Sentiero Monterosso–Vernazza (moderate, views).",
      "Sciacchetrà wine tasting in small cantinas (book ahead).",
      "Portovenere as a day trip (UNESCO together with Cinque Terre).",
      "Use morning light in the villages before day-trippers arrive.",
    ],
    history: [
      "Wine terraces on the Ligurian cliff are attested since Roman times; today’s villages grew in the High Middle Ages under Genoese rule.",
      "In 1874 the Genoa–La Spezia railway opened and partly replaced hard sea transport; trails were formalised (national park since 1999).",
      "In 1997 UNESCO listed the Cinque Terre cultural landscape and coast; the 2011 floods destroyed paths and led to restoration and visitor management.",
    ],
  },
  "cote-dazur": {
    name: "Côte d'Azur",
    story: [
      "Five nights in steps: Nice, Mougins or Cannes, then the Saint-Tropez area – with Plage Keller on Cap d’Antibes.",
      "Grimaud, Port Grimaud and Ramatuelle instead of harbour rush; arrive by car from Italy or fly into Nice.",
    ],
    mustSee: [
      "1 night near Nice after arrival.",
      "Plage Keller: lunch on Cap d’Antibes.",
      "Drive the Cannes–Antibes coast road slowly.",
      "Picasso: Musée Antibes and Vallauris.",
      "2 nights at Hotel de Mougins or in Cannes.",
      "Saint-Tropez harbour only early.",
      "Port Grimaud: canals on foot.",
      "Grimaud: castle village above the gulf.",
      "Ramatuelle: village and beach.",
      "2 nights in the Saint-Tropez area – our Provence route fits afterwards.",
    ],
    history: [
      "In the 18th/19th centuries the Riviera became a winter quarter for British and Russian aristocracy; Nice’s Promenade des Anglais still carries that name.",
      "Picasso lived and worked in the region (Antibes, Vallauris, later Mougins) and shaped the local art scene.",
      "Today the Côte d’Azur mixes the coast road, yacht tourism and hinterland villages – high season and festival weeks need early booking.",
    ],
  },
  provence: {
    name: "Provence",
    story: [
      "Avignon, ochre in the Luberon, markets in Aix and the Verdon: Provence works best with few bases.",
      "Our 6-day route plans five nights and treats lavender honestly as a seasonal extra.",
    ],
    mustSee: [
      "Avignon: Palais des Papes and old town as a compact start.",
      "Gordes: views and two nights as a Luberon base.",
      "Roussillon: ochre trail early in the day.",
      "Lourmarin: quieter extra south of the Luberon.",
      "Aix-en-Provence: market, squares and a car-free city day.",
      "Valensole: plan only in season as a lavender stop.",
      "Moustiers-Sainte-Marie: base before the Verdon.",
      "Pont du Galetas: access to the Verdon Gorge depending on weather.",
      "Four hotel bases instead of daily suitcase moves.",
      "Check heat, wildfire and road notices at short notice.",
    ],
    history: [
      "Avignon was the papal seat from 1309 to 1377; the Palais des Papes still shapes the walled old town.",
      "The Luberon joins historic villages with a landscape shaped by farming over centuries; ochre mining formed places such as Roussillon.",
      "Aix-en-Provence was capital of historic Provence. Today Roman traces, markets and the heritage linked to Paul Cézanne meet a modern university city.",
    ],
  },
  "grandes-alpes": {
    name: "Route des Grandes Alpes",
    story: [
      "Seven nights from Geneva to Cannes: one valley each evening, Iseran and Bonette as days of their own.",
      "Passes instead of the motorway – Cannes only when the mountains are behind you.",
    ],
    mustSee: [
      "Col des Aravis or Colombière after Geneva.",
      "1 night in Megève or Grand-Bornand.",
      "Cormet de Roselend with a lake stop.",
      "1 night in Val-d'Isère or Séez – Iseran the next morning.",
      "Col de l'Iseran and Col du Galibier in one day.",
      "Briançon: Vauban old town on foot.",
      "Col d'Izoard and Casse Déserte as a short stage.",
      "Cime de la Bonette including the ridge loop.",
      "1 night in Saint-Martin-Vésubie before the sea.",
      "Cannes: Suquet, not Croisette rush.",
    ],
    history: [
      "The Route des Grandes Alpes was developed from 1911 as a north–south tourist link across the French Alps; many cols were mule tracks or military roads before.",
      "Col de l'Iseran (opened to traffic in 1937) remains the highest paved Alpine pass; Cime de la Bonette completes the chain in the south as Europe’s highest paved road.",
      "Today the route is seasonal (often June–September) and part of Tour de France lore – closures and motorbike traffic belong to pass season.",
    ],
  },
};
