import type { InspirationCopy } from "@/lib/inspirationCopy";

export const INSPIRATION_COPY_ES: Record<string, InspirationCopy> = {
  santorini: {
    name: "Santorini",
    story: [
      "Casas blancas, cúpulas azules y la vista a la caldera: Santorini parece una postal hecha vida.",
      "Las tardes en Oia, cuando el sol se hunde en el mar, se quedan. De día: viñedos, calas pequeñas y la historia de una isla volcánica.",
    ],
    mustSee: [
      "Akrotiri: ciudad minoica enterrada tras la erupción de la Edad del Bronce (excavación, horario fijo).",
      "Vista de la caldera desde Fira o Imerovigli, sobre todo al caer la luz.",
      "Oia al atardecer: planifica la puesta de sol desde las ruinas de Agios Nikolaos.",
      "Museo Arqueológico de Fira: frescos y hallazgos de Akrotiri de un vistazo.",
      "Museo de la Tera prehistórica: geología y contexto del poblamiento.",
      "Cata de vinos en Pyrgos o Megalochori (Assyrtiko, Aidani).",
      "Islote volcánico Nea Kameni: excursión en barco con un corto paseo al cráter.",
      "Bahía de Amoudi bajo Oia: bajada empinada, tabernas de pescado junto al agua.",
      "Monasterio del Profeta Elías (punto más alto): vistas a las Cícladas.",
      "Antigua Tera en Mesa Vouno: ruinas clásico-romanas sobre el mar.",
    ],
    history: [
      "En el Bronce Tardío había en Tera una ciudad de influjo minoico (Akrotiri); la gran erupción en la segunda mitad del II milenio a. C. enterró el asentamiento bajo piedra pómez y ceniza y formó la caldera actual.",
      "En la Antigüedad la isla se llamaba Tera; en la Edad Media se instalaron venecianos y dejaron recintos fortificados como Pyrgos. De 1566 a 1821 la isla cicládica perteneció al Imperio otomano.",
      "En 1830 Tera pasó al Estado griego independiente; el turismo masivo llegó en el siglo XX, con debates sobre capacidad, agua y protección del patrimonio.",
    ],
  },
  nordlichter: {
    name: "Auroras boreales",
    story: [
      "Bandas verde-violeta en el cielo nocturno: la aurora es una experiencia natural que muchos viajeros quieren vivir una vez.",
      "Las mejores opciones están dentro del círculo polar en la temporada oscura, con paciencia, ropa abrigada y una ruta flexible.",
    ],
    mustSee: [
      "Tromsø (Noruega): temporada de auroras de septiembre a marzo, muchas excursiones guiadas al interior.",
      "Abisko (Suecia): noches estadísticamente más despejadas por el föhn de las montañas.",
      "Región de Rovaniemi (Finlandia): granjas de renos y caza de auroras.",
      "Lofoten: fiordos y pueblos pesqueros bajo la aurora (según el tiempo).",
      "Senja: más tranquila que Tromsø, costa escarpada.",
      "Kiruna y la zona del Icehotel: noches polares largas, buena infraestructura.",
      "Islandia (Þingvellir, costa sur): aurora junto a géiseres y glaciares (sin garantía).",
      "Fairbanks (Alaska): frío continental, noches de invierno claras.",
      "Yellowknife (Canadá): turismo de auroras consolidado.",
      "Usa previsiones de clima espacial (p. ej. NOAA OVATION, apps locales), no solo el tiempo.",
    ],
    history: [
      "Fuentes nórdicas (Snorri Sturluson, s. XIII) vinculan la aurora al mito; cronistas europeos medievales leían a menudo las auroras rojas como malos presagios.",
      "Desde el siglo XVII los naturalistas las relacionaron con el campo magnético terrestre; hacia 1900 Kristian Birkeland modeló partículas solares que entran en la atmósfera polar y excitan el gas (el verde del oxígeno es típico).",
      "Los satélites miden viento solar y CME; los viajes se concentran en latitudes geomagnéticas 65–75° N en la temporada de equinoccio e invierno.",
    ],
  },
  venedig: {
    name: "Venecia",
    story: [
      "Góndolas, callejones y serenatas en las plazas: Venecia es un laberinto de agua y piedra.",
      "Más allá de Rialto y San Marcos, merece la pena perderse por Cannaregio: menos aglomeración, más vida cotidiana.",
    ],
    mustSee: [
      "Basílica de San Marcos y Campanile (planifica entradas y colas).",
      "Palacio Ducal por el Puente de los Suspiros hasta la cárcel.",
      "Puente de Rialto y Mercato di Rialto por la mañana.",
      "Puente de la Accademia: vista clásica del Canal Grande.",
      "Basílica de Santa Maria della Salute (iglesia votiva de la peste, 1631–1687).",
      "Ghetto Nuovo: primer barrio judío residencial documentado de Europa (1516).",
      "Scuola Grande di San Rocco: ciclos de Tintoretto.",
      "Jardines de la Bienal (Giardini) y Arsenale en años de bienal de arte.",
      "Vaporetto línea 1: todo el Canal Grande como trayecto.",
      "Murano (vidrio) y Burano (encaje, color) en barco.",
    ],
    history: [
      "Las islas de la laguna se poblaron desde la Antigüedad tardía; tras influjos longobardos y bizantinos, la comunidad eligió según la tradición al primer dux en 697 y creció como república marítima.",
      "En la plena Edad Media y la Edad Moderna Venecia controló rutas comerciales hacia el Mediterráneo oriental; la Cuarta Cruzada de 1204 acabó con la toma de Constantinopla bajo liderazgo véneto-francés.",
      "En 1797 la república se rindió a Napoleón (Tratado de Campo Formio); luego dominio austriaco y, desde 1866, unión al Reino de Italia. Las barreras MOSE en las bocas de la laguna entraron en servicio en 2020.",
    ],
  },
  malediven: {
    name: "Maldivas",
    story: [
      "Agua turquesa, arena fina y atolones: las Maldivas significan calma y mundos submarinos.",
      "Snorkel y buceo desde el bungalow hacen inolvidable muchas estancias.",
    ],
    mustSee: [
      "Snorkel en el arrecife de la casa (tiburones/rayas solo con guía y normas).",
      "Playas de bioluminiscencia (Vaadhoo y otras, según luna y plancton).",
      "Centro cultural maldivo en Malé: construcción de barcos y vida cotidiana.",
      "Hukuru Miskiiy (mezquita del viernes, 1656) en Malé, con talla en coral.",
      "Puntos de buceo: Banana Reef, Manta Point (comprueba la temporada).",
      "Salto de islas en lancha o vuelo interior más hidroavión.",
      "Bancos de arena en marea baja para fotos: vigila la corriente.",
      "Thoddoo: isla agrícola con melones (excursiones para huéspedes).",
      "Atolón Addu: antigua instalación de radar británica, rutas en bici.",
      "Revisa la sostenibilidad (solar, desalación, residuos del resort).",
    ],
    history: [
      "Hay una época budista desde c. el siglo V d. C. atestiguada arqueológicamente; el paso al islam se data en 1153 (tradición del primer sultán musulmán).",
      "Presencia portuguesa breve en 1558, luego influjo neerlandés indirecto; en 1887 protectorado británico sobre el sultán. Independencia el 26 de julio de 1965, república en 1968.",
      "El tsunami de 2004 devastó muchas islas bajas; desde entonces hay rellenos y islas turísticas con zonificación estricta.",
    ],
  },
  paris: {
    name: "París",
    story: [
      "Ciudad de la luz, museos y cafés: París une iconos como la Torre Eiffel y el Louvre con el encanto de barrio.",
      "Un paseo por el Sena o por Le Marais suele traer los mejores momentos imprevistos.",
    ],
    mustSee: [
      "Louvre (reserva franja horaria) y Jardín de las Tullerías.",
      "Musée d’Orsay en la antigua estación (impresionismo).",
      "Notre-Dame (exterior y fachada oeste accesibles de nuevo tras el incendio de 2019; el interior depende de la fase).",
      "Sainte-Chapelle: vidrieras góticas en la Île de la Cité.",
      "Versalles en RER C (palacio y jardines, al menos medio día).",
      "Montmartre: Sacré-Cœur y Place du Tertre.",
      "Marais: Place des Vosges y el barrio judío en torno a Rue des Rosiers.",
      "Promenade Plantée / Coulée Verte como parque lineal sobre un viaducto.",
      "Catacumbas (estrechas, entradas por adelantado).",
      "Recorre las orillas UNESCO del Sena entre Pont de Sully y Pont d’Iéna.",
    ],
    history: [
      "Los parisii celtas se instalaron en la isla del Sena; Lutetia romana desde el siglo I d. C. con foro y termas. Carlomagno convocó una asamblea en 798 en la capilla palatina.",
      "Los capetos hicieron de París residencia; en 1789 el pueblo tomó la Bastilla. El barón Haussmann construyó bulevares y alcantarillado bajo Napoleón III a mediados del XIX.",
      "Los asedios de 1870/71 y la Comuna marcaron la Tercera República; ciudad y suburbios crecieron administrativamente (Grand Paris desde 2016).",
    ],
  },
  barcelona: {
    name: "Barcelona",
    story: [
      "Gaudí, playa y cocina catalana: Barcelona mezcla gran ciudad con aire mediterráneo.",
      "Del Park Güell al Barri Gòtic se recorre bien en transporte público y a pie.",
    ],
    mustSee: [
      "Sagrada Família (entrada online obligatoria).",
      "Park Güell (la zona visitada requiere entrada).",
      "Casa Batlló y Casa Milà (La Pedrera) en el Passeig de Gràcia.",
      "Barri Gòtic: catedral, Plaça del Rei con palacios medievales.",
      "Museu Picasso en El Born.",
      "Palau de la Música Catalana (Modernisme, visitas guiadas).",
      "Montjuïc: Fundació Joan Miró, Estadio Olímpico, Fuente Mágica (horarios).",
      "Playa de la Barceloneta y paseo del puerto.",
      "Camp Nou / Spotify Camp Nou (visita al estadio según las obras).",
      "Mercat de la Boquería o Santa Caterina para desayunar en el mercado.",
    ],
    history: [
      "La Colonia Iulia Augusta Faventia Paterna Barcino romana nació bajo Augusto; en la Edad Media Barcelona fue capital del condado de Barcelona en la Corona de Aragón.",
      "Tras la unión Aragón-Castilla, Cataluña siguió fuerte económicamente; en la Guerra de Sucesión de 1714 la ciudad cayó tras un asedio ante las tropas borbónicas (Diada).",
      "La industria del siglo XIX financió el Modernisme (Gaudí y otros); los Juegos de 1992 impulsaron costa e infraestructuras.",
    ],
  },
  amalfi: {
    name: "Amalfi",
    story: [
      "Costa escarpada, limonares y pueblos de color: la Costa Amalfitana es el clásico italiano de road trip con mar.",
      "Entre Positano y Vietri sul Mare cada curva espera un panorama nuevo: esboza ruta y paradas de antemano.",
    ],
    mustSee: [
      "Positano: Chiesa di Santa Maria Assunta con cúpula de mayólica.",
      "Sendero de los Dioses (Sentiero degli Dei): caminata Bomerano–Nocelle (logística de autobús).",
      "Amalfi: catedral de Sant’Andrea con el Claustro del Paraíso.",
      "Ravello: Villa Rufolo y Villa Cimbrone (jardines en terraza).",
      "Maiori / Minori: huellas de villa marítima romana, menos masificados.",
      "Vietri sul Mare: talleres de cerámica.",
      "Barco de Salerno a Amalfi/Positano (horario de verano).",
      "Fiordo di Furore: desfiladero estrecho con puente en la SS163 (foto, atención al tráfico).",
      "Strada Statale 163: fácil para autobuses, estrés en coche: deja margen.",
      "Producción de limoncello en Minori o Tramonti (reserva).",
    ],
    history: [
      "En la Alta Edad Media Amalfi se convirtió en república mercantil marítima (de facto s. IX–XI) con factorías en el Mediterráneo oriental; las Tablas amalfitanas (fragmentos de derecho marítimo, conservados p. ej. en Pisa y Rávena) se vinculan a Amalfi.",
      "La conquista normanda del sur de Italia (s. XI) y más tarde la batalla de Meloria (1284) debilitaron la flota; las pestes del siglo XIV redujeron la población.",
      "En 1997 la UNESCO inscribió la Costa Amalfitana como paisaje cultural (huertos en terraza, poblamiento en laderas).",
    ],
  },
  hallstatt: {
    name: "Hallstatt",
    story: [
      "Reflejos en el lago, minas de sal y telón alpino: Hallstatt atrae con su idilio de postal.",
      "Llegar pronto o tarde merece la pena si quieres calma: el pueblo es pequeño, la vista es grande.",
    ],
    mustSee: [
      "Mirador del patrimonio (vista de postal) al amanecer o al anochecer.",
      "Salzwelten Hallstatt: descenso en tren minero (entradas).",
      "Museo de palafitos junto al lago (UNESCO, palafitos alpinos).",
      "Osario de San Miguel con huesos apilados (horario).",
      "Plaza del mercado con fachadas de madera e iglesia protestante Christuskirche.",
      "Paseo lacustre hacia Lahn (más tranquilo que el centro).",
      "Dachstein-Krippenstein: plataforma Five Fingers (bus/tren).",
      "Gosausee como excursión de día (coche o bus).",
      "Bad Aussee o Altaussee para el paisaje del Salzkammergut cercano.",
      "Paseo en barco por el lago de Hallstatt (temporada).",
    ],
    history: [
      "La minería de sal en el Salzberg de Hallstatt está atestiguada en la cultura de los Campos de Urnas; el término «periodo de Hallstatt» (c. 800–450 a. C.) nace de este yacimiento.",
      "Celtas y luego romanos usaron el yacimiento; en la Edad Media los Habsburgo controlaban la mina. En 1595 casi todo el pueblo ardió y se reconstruyó en la orilla actual.",
      "En 1997 la UNESCO inscribió el paisaje Hallstatt-Dachstein/Salzkammergut; desde los años 2010 el municipio debate el sobreturismo y los límites de autobuses.",
    ],
  },
  dubrovnik: {
    name: "Dubrovnik",
    story: [
      "Murallas, Adriático y adoquines: Dubrovnik une historia con aire mediterráneo.",
      "El casco antiguo es compacto: perfecto para un día sin prisa y luego seguir planeando la costa.",
    ],
    mustSee: [
      "Recorrido de murallas (una entrada, horario fijo).",
      "Stradun (Placa) como eje principal.",
      "Palacio del Rector (museo de historia cultural).",
      "Convento franciscano con una de las farmacias en uso más antiguas de Europa.",
      "Palacio Sponza (archivo / sala conmemorativa 1991–1995).",
      "Fuerte Lovrijenac al oeste del casco (vista de fortaleza).",
      "Teleférico del Srđ: panorama sobre los tejados.",
      "Isla de Lokrum (jardín botánico, réplica del Trono de Hierro).",
      "Playa Banje o kayak bajo las murallas.",
      "Localizaciones de Juego de Tronos opcional con franja temprana (menos grupos).",
    ],
    history: [
      "Como Ragusa, la república urbana gestionó desde el siglo XIV un amplio comercio marítimo; en 1416 prohibió el comercio de esclavos, temprano para ciudades mediterráneas.",
      "Un terremoto en 1667 destruyó gran parte; la silueta barroca nació en la reconstrucción. La independencia acabó en 1808; en 1815 Ragusa pasó a Austria, en 1918 a Yugoslavia.",
      "En 1991 el JNA bombardeó el casco (UNESCO desde 1979); tras la guerra de Croacia vino una restauración cuidadosa de la piedra. En 2023 la ciudad adoptó el euro.",
    ],
  },
  "cinque-terre": {
    name: "Cinque Terre",
    story: [
      "Cinco pueblos de color entre acantilado y mar de Liguria: Cinque Terre es un clásico de senderismo y tren.",
      "Caminos como el Blue Trail unen los pueblos: buen calzado y entradas por adelantado evitan estrés.",
    ],
    mustSee: [
      "Monterosso al Mare: la única playa de arena, acceso en tren.",
      "Vernazza: cala del puerto con ruina de torre Castello Doria.",
      "Corniglia: más de 380 escalones «Lardarina» desde la estación.",
      "Manarola: mirador de postal sobre el viñedo.",
      "Riomaggiore: Via dell’Amore (tramos según la restauración).",
      "Comprueba el Cinque Terre Card para senderos y trenes.",
      "Sentiero Monterosso–Vernazza (dificultad media, vistas).",
      "Cata de Sciacchetrà en cantinas pequeñas (reserva).",
      "Portovenere como excursión de día (UNESCO junto con Cinque Terre).",
      "Aprovecha la luz de la mañana en los pueblos antes de los excursionistas.",
    ],
    history: [
      "Las terrazas de viña en el acantilado ligur están atestiguadas desde época romana; los pueblos actuales crecieron en la plena Edad Media bajo dominio genovés.",
      "En 1874 se abrió la línea Génova–La Spezia y sustituyó en parte el duro transporte marítimo; los senderos se formalizaron (parque nacional desde 1999).",
      "En 1997 la UNESCO inscribió el paisaje cultural de Cinque Terre y la costa; las inundaciones de 2011 destruyeron caminos y llevaron a restauración y gestión de visitantes.",
    ],
  },
  "cote-dazur": {
    name: "Costa Azul",
    story: [
      "Cinco noches en etapas: Niza, Mougins o Cannes, luego la zona de Saint-Tropez, con Plage Keller en el Cap d’Antibes.",
      "Grimaud, Port Grimaud y Ramatuelle en vez de solo prisas en el puerto; llegada en coche desde Italia o vuelo a Niza.",
    ],
    mustSee: [
      "1 noche cerca de Niza tras la llegada.",
      "Plage Keller: almuerzo en el Cap d’Antibes.",
      "Conduce despacio la costa Cannes–Antibes.",
      "Picasso: Musée Antibes y Vallauris.",
      "2 noches en Hotel de Mougins o en Cannes.",
      "Puerto de Saint-Tropez solo temprano.",
      "Port Grimaud: canales a pie.",
      "Grimaud: pueblo-castillo sobre el golfo.",
      "Ramatuelle: pueblo y playa.",
      "2 noches en la zona de Saint-Tropez; después encaja nuestra ruta de Provenza.",
    ],
    history: [
      "En los siglos XVIII y XIX la Riviera fue cuartel de invierno de la aristocracia británica y rusa; el Promenade des Anglais de Niza conserva ese nombre.",
      "Picasso vivió y trabajó en la región (Antibes, Vallauris, luego Mougins) y marcó la escena artística local.",
      "Hoy la Costa Azul une carretera costera, turismo de yates y pueblos del interior: alta temporada y semanas de festival piden reserva temprana.",
    ],
  },
  provence: {
    name: "Provenza",
    story: [
      "Aviñón, ocre en el Luberon, mercados en Aix y el Verdon: la Provenza funciona mejor con pocas bases.",
      "Nuestra ruta de 6 días planifica cinco noches y trata la lavanda con honestidad, como extra de temporada.",
    ],
    mustSee: [
      "Aviñón: Palacio de los Papas y casco antiguo como arranque compacto.",
      "Gordes: vistas y dos noches como base del Luberon.",
      "Roussillon: sendero de ocre temprano.",
      "Lourmarin: extra más tranquilo al sur del Luberon.",
      "Aix-en-Provence: mercado, plazas y un día de ciudad sin coche.",
      "Valensole: solo en temporada como parada de lavanda.",
      "Moustiers-Sainte-Marie: base antes del Verdon.",
      "Pont du Galetas: acceso a las Gargantas del Verdon según el tiempo.",
      "Cuatro bases hoteleras en vez de cambiar de maleta cada día.",
      "Revisa calor, incendios forestales y avisos de carretera a corto plazo.",
    ],
    history: [
      "Aviñón fue sede papal de 1309 a 1377; el Palacio de los Papas sigue marcando el casco amurallado.",
      "El Luberon une pueblos históricos con un paisaje agrícola de siglos; la minería de ocre formó lugares como Roussillon.",
      "Aix-en-Provence fue capital de la Provenza histórica. Hoy coinciden huellas romanas, mercados y el legado vinculado a Paul Cézanne con una ciudad universitaria moderna.",
    ],
  },
  "grandes-alpes": {
    name: "Ruta de los Grandes Alpes",
    story: [
      "Siete noches de Ginebra a Cannes: un valle cada tarde, Iseran y Bonette como días propios.",
      "Puertos en vez de autopista: Cannes solo cuando las montañas quedan atrás.",
    ],
    mustSee: [
      "Col des Aravis o Colombière tras Ginebra.",
      "1 noche en Megève o Grand-Bornand.",
      "Cormet de Roselend con parada en el lago.",
      "1 noche en Val-d'Isère o Séez: el Iseran a la mañana siguiente.",
      "Col de l'Iseran y Col du Galibier en un día.",
      "Briançon: casco Vauban a pie.",
      "Col d'Izoard y Casse Déserte como etapa corta.",
      "Cime de la Bonette con el bucle de cresta.",
      "1 noche en Saint-Martin-Vésubie antes del mar.",
      "Cannes: Suquet, no prisas en la Croisette.",
    ],
    history: [
      "La Route des Grandes Alpes se desarrolló desde 1911 como enlace turístico norte–sur por los Alpes franceses; muchos puertos eran caminos de herradura o vías militares.",
      "El Col de l'Iseran (abierto al tráfico en 1937) sigue siendo el puerto asfaltado más alto de los Alpes; la Cime de la Bonette cierra la cadena al sur como la carretera asfaltada más alta de Europa.",
      "Hoy la ruta es de temporada (a menudo junio–septiembre) y parte del mito del Tour: cierres y motos forman parte de la temporada de puertos.",
    ],
  },
};
